name: Release to Ballerina Central

on:
  workflow_dispatch:
    inputs:
      ballerina_version:
        description: 'Ballerina version to use (e.g., 2201.8.0, latest, nightly)'
        required: false
        default: 'latest'
        type: string
      packages:
        description: 'Packages to release (comma-separated, or "all" for all packages)'
        required: true
        default: 'all'
        type: string
      bal_central_environment:
        description: 'Environment to release to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - STAGING
          - PROD

jobs:
  discover-packages:
    runs-on: ubuntu-latest
    outputs:
      package_list: ${{ steps.find-packages.outputs.packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find Ballerina packages
        id: find-packages
        run: |
          package_dirs=$(find . -maxdepth 2 -name "Ballerina.toml" -exec dirname {} \; | sort | sed 's/.\///')
          package_list=$(echo "$package_dirs" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "packages=$package_list" >> $GITHUB_OUTPUT
          echo "Found packages: $package_list"

  release:
    needs: discover-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.discover-packages.outputs.package_list) }}
        include: []
    if: |
      github.event.inputs.packages == 'all' || 
      contains(split(github.event.inputs.packages, ','), matrix.package)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: ${{ github.event.inputs.ballerina_version || 'latest' }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Ballerina package
        run: |
          cd ${{ matrix.package }}
          bal pack

      - name: Push to Dev
        if: github.event.inputs.bal_central_environment == 'DEV'
        run: bal push
        working-directory: ./${{ matrix.package }}
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Push to Staging
        if: github.event.inputs.bal_central_environment == 'STAGING'
        run: bal push
        working-directory: ./${{ matrix.package }}
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGING_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Push to Production
        if: github.event.inputs.bal_central_environment == 'PROD'
        run: bal push
        working-directory: ./${{ matrix.package }}
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_PROD_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm
